import type { PathResponse } from "@jose/shared";

/** Demo curriculum + progress for Work and Life of Rizal. */
export const DEMO_PATH: PathResponse = {
  course: {
    id: "rizal",
    title: "Work and Life of Rizal",
  },
  learner: {
    displayName: "Explorer",
    streak: 3,
    hearts: 5,
    xp: 120,
  },
  sections: [
    {
      id: "childhood",
      title: "Childhood",
      subtitle: "Calamba beginnings",
      themeColor: "#A855F7",
      nodes: [
        {
          id: "childhood-born",
          title: "Born in Calamba",
          kind: "lesson",
          status: "completed",
          icon: "check",
          position: "center",
        },
        {
          id: "childhood-family",
          title: "The Mercado family",
          kind: "lesson",
          status: "completed",
          icon: "check",
          position: "left",
        },
        {
          id: "childhood-stories",
          title: "Stories from Teodora",
          kind: "lesson",
          status: "completed",
          icon: "check",
          position: "right",
        },
        {
          id: "childhood-chest",
          title: "Childhood treasure",
          kind: "chest",
          status: "completed",
          icon: "chest",
          position: "center",
        },
      ],
    },
    {
      id: "education",
      title: "Education",
      subtitle: "Biñan to Madrid",
      themeColor: "#22C55E",
      nodes: [
        {
          id: "edu-binan",
          title: "School in Biñan",
          kind: "lesson",
          status: "completed",
          icon: "check",
          position: "center",
        },
        {
          id: "edu-ateneo",
          title: "Ateneo Municipal",
          kind: "lesson",
          status: "current",
          icon: "book",
          position: "left",
        },
        {
          id: "edu-ust",
          title: "University of Santo Tomas",
          kind: "lesson",
          status: "locked",
          icon: "book",
          position: "right",
        },
        {
          id: "edu-madrid",
          title: "Studies in Madrid",
          kind: "lesson",
          status: "locked",
          icon: "star",
          position: "center",
        },
      ],
    },
    {
      id: "travels",
      title: "Travels",
      subtitle: "Europe and beyond",
      themeColor: "#38BDF8",
      nodes: [
        {
          id: "travel-paris",
          title: "Paris days",
          kind: "lesson",
          status: "locked",
          icon: "book",
          position: "left",
        },
        {
          id: "travel-germany",
          title: "Germany & science",
          kind: "lesson",
          status: "locked",
          icon: "book",
          position: "right",
        },
        {
          id: "travel-chest",
          title: "Traveler's chest",
          kind: "chest",
          status: "locked",
          icon: "chest",
          position: "center",
        },
      ],
    },
    {
      id: "novels",
      title: "Noli & Fili",
      subtitle: "Novels and reform",
      themeColor: "#F97316",
      nodes: [
        {
          id: "noli",
          title: "Noli Me Tangere",
          kind: "lesson",
          status: "locked",
          icon: "book",
          position: "center",
        },
        {
          id: "fili",
          title: "El Filibusterismo",
          kind: "lesson",
          status: "locked",
          icon: "book",
          position: "left",
        },
        {
          id: "reform",
          title: "La Liga Filipina",
          kind: "lesson",
          status: "locked",
          icon: "star",
          position: "right",
        },
      ],
    },
    {
      id: "martyrdom",
      title: "Martyrdom",
      subtitle: "Trial and Bagumbayan",
      themeColor: "#EF4444",
      nodes: [
        {
          id: "arrest",
          title: "Arrest & trial",
          kind: "lesson",
          status: "locked",
          icon: "book",
          position: "center",
        },
        {
          id: "mi-ultimo",
          title: "Mi Último Adiós",
          kind: "lesson",
          status: "locked",
          icon: "star",
          position: "left",
        },
        {
          id: "bagumbayan",
          title: "Bagumbayan",
          kind: "lesson",
          status: "locked",
          icon: "book",
          position: "right",
        },
        {
          id: "legacy-chest",
          title: "Legacy chest",
          kind: "chest",
          status: "locked",
          icon: "chest",
          position: "center",
        },
      ],
    },
  ],
};
